//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Y_POS.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Y_POS.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Action_Break {
            get {
                return ResourceManager.GetString("Action_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In.
        /// </summary>
        public static string Action_ClockIn {
            get {
                return ResourceManager.GetString("Action_ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Out.
        /// </summary>
        public static string Action_ClockOut {
            get {
                return ResourceManager.GetString("Action_ClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close &amp; New Order.
        /// </summary>
        public static string Action_CloseAndNewOrder {
            get {
                return ResourceManager.GetString("Action_CloseAndNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Order.
        /// </summary>
        public static string Action_CloseOrder {
            get {
                return ResourceManager.GetString("Action_CloseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string Action_NewOrder {
            get {
                return ResourceManager.GetString("Action_NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Orders.
        /// </summary>
        public static string ActiveOrders {
            get {
                return ResourceManager.GetString("ActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string CashDrawer_AmountUpdateReason {
            get {
                return ResourceManager.GetString("CashDrawer_AmountUpdateReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by amount.
        /// </summary>
        public static string CashdrawerCheck_ByAmount {
            get {
                return ResourceManager.GetString("CashdrawerCheck_ByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by bill type.
        /// </summary>
        public static string CashdrawerCheck_ByBillType {
            get {
                return ResourceManager.GetString("CashdrawerCheck_ByBillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string CashDrawerSummary_Balance {
            get {
                return ResourceManager.GetString("CashDrawerSummary_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Withdraw.
        /// </summary>
        public static string CashDrawerSummary_BankWidthdraw {
            get {
                return ResourceManager.GetString("CashDrawerSummary_BankWidthdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In.
        /// </summary>
        public static string CashDrawerSummary_CashIn {
            get {
                return ResourceManager.GetString("CashDrawerSummary_CashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Out.
        /// </summary>
        public static string CashDrawerSummary_CashOut {
            get {
                return ResourceManager.GetString("CashDrawerSummary_CashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Cashier In.
        /// </summary>
        public static string CashDrawerSummary_LastCashierIn {
            get {
                return ResourceManager.GetString("CashDrawerSummary_LastCashierIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Cashier Out.
        /// </summary>
        public static string CashDrawerSummary_LastCashierOut {
            get {
                return ResourceManager.GetString("CashDrawerSummary_LastCashierOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Check.
        /// </summary>
        public static string CashDrawerSummary_LastCheck {
            get {
                return ResourceManager.GetString("CashDrawerSummary_LastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string CashDrawerSummary_Sales {
            get {
                return ResourceManager.GetString("CashDrawerSummary_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coins.
        /// </summary>
        public static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Discount.
        /// </summary>
        public static string CustomDiscount {
            get {
                return ResourceManager.GetString("CustomDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string Date_Time {
            get {
                return ResourceManager.GetString("Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card.
        /// </summary>
        public static string GiftCard {
            get {
                return ResourceManager.GetString("GiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Orders.
        /// </summary>
        public static string Navigation_ActiveOrders {
            get {
                return ResourceManager.GetString("Navigation_ActiveOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashdrawer.
        /// </summary>
        public static string Navigation_Cashdrawer {
            get {
                return ResourceManager.GetString("Navigation_Cashdrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Orders.
        /// </summary>
        public static string Navigation_ClosedOrders {
            get {
                return ResourceManager.GetString("Navigation_ClosedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Navigation_Quit {
            get {
                return ResourceManager.GetString("Navigation_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Navigation_Reports {
            get {
                return ResourceManager.GetString("Navigation_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Navigation_Settings {
            get {
                return ResourceManager.GetString("Navigation_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cashdrawer.
        /// </summary>
        public static string OpenCashdrawer {
            get {
                return ResourceManager.GetString("OpenCashdrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was successfully paid!.
        /// </summary>
        public static string OrderPaidSuccess {
            get {
                return ResourceManager.GetString("OrderPaidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo.
        /// </summary>
        public static string Promo {
            get {
                return ResourceManager.GetString("Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customer.
        /// </summary>
        public static string Search_Customer {
            get {
                return ResourceManager.GetString("Search_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All on One.
        /// </summary>
        public static string Split_AllOnOne {
            get {
                return ResourceManager.GetString("Split_AllOnOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Seats.
        /// </summary>
        public static string Split_BySeats {
            get {
                return ResourceManager.GetString("Split_BySeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenly.
        /// </summary>
        public static string Split_Evenly {
            get {
                return ResourceManager.GetString("Split_Evenly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member.
        /// </summary>
        public static string StaffMember {
            get {
                return ResourceManager.GetString("StaffMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
    }
}
